//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoyalFilial.Framework.Core.Util.TypeConversion
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TC {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TC() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LoyalFilial.Framework.Core.Util.TypeConversion.TC", typeof(TC).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConvertFromException={0} cannot convert from {1}..
        /// </summary>
        internal static string ConvertFromException {
            get {
                return ResourceManager.GetString("ConvertFromException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConvertInvalidPrimitive={0} is not a valid value for {1}..
        /// </summary>
        internal static string ConvertInvalidPrimitive {
            get {
                return ResourceManager.GetString("ConvertInvalidPrimitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConvertToException=&apos;{0}&apos; is unable to convert &apos;{1}&apos; to &apos;{2}&apos;..
        /// </summary>
        internal static string ConvertToException {
            get {
                return ResourceManager.GetString("ConvertToException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified type is not a nullable type..
        /// </summary>
        internal static string NullableConverterBadCtorArg {
            get {
                return ResourceManager.GetString("NullableConverterBadCtorArg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToStringNull=(null).
        /// </summary>
        internal static string ToStringNull {
            get {
                return ResourceManager.GetString("ToStringNull", resourceCulture);
            }
        }
    }
}
